name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in medium posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@rajatrokde/"

  jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update README with Hashnode post
        env:
          HASHNODE_API_TOKEN: ${{ secrets.HASHNODE_API_TOKEN }}
        run: |
          # Replace `rajatrokde` with your Hashnode username and `YOUR_HASHNODE_POST_SLUG` with the post's slug
          # Make sure you have the 'curl' command available in the system (most systems have it pre-installed)
          curl -X POST -H "Content-Type: application/json" -H "Authorization: $HASHNODE_API_TOKEN" -d '{"username":"rajatrokde","slug":"/"}' https://api.hashnode.com/

      - name: Commit and push changes
        run: |
          git config --global user.name "rajatrokde"
          git config --global user.email "rajatrokde01@gmail.com"
          git add README.md
          git commit -m "Update README with Hashnode post"
          git push
